apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev-cluster
  region: us-east-2

managedNodeGroups:
- name: spot
  instanceTypes: ["c4.large","c5.large","c5d.large","c5n.large","c5a.large"]
  spot: true
  desiredCapacity: 2
  volumeSize: 10
  ssh:
    allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
