apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argocd
spec:
  gateways:
  - istio-ingressgateway
  hosts:
  - argo.dev.thomasbuilds.technology
  http:
  - route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
