apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ops
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/thomasv314/infra-eks.git
    targetRevision: HEAD
    path: applications/cert-manager
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: certificaterequests.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: certificates.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: challenges.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: challenges.acme.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterissuers.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: issuers.cert-manager.io
      jsonPointers:
        - /status
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: orders.acme.cert-manager.io
      jsonPointers:
        - /status
