apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ops
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/thomasv314/infra-eks.git
    targetRevision: HEAD
    path: applications/external-dns
    helm:
      parameters:
        - name: "external-dns.domainFilters"
          value: '{{ "{" }}{{ .Values.domain }}{{ "}" }}'
        - name: "external-dns.fqdnTemplates"
          value: '{{ "{{" }}.Name{{ "}}" }}.{{ .Values.domain }}'

  syncPolicy:
    automated:
      prune: true
    validate: true
