apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ops
    server: {{ .Values.spec.destination.server }}
  project: default

  helm:
    parameters:
      - name: "domainFilters"
        value: "\{{{ .Values.domain }}\}"

  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: external-dns
    targetRevision: 5.0.0
  syncPolicy:
    automated:
      prune: true
    validate: true
