apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: istio-system
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/thomasv314/infra-eks.git
    targetRevision: HEAD
    path: applications/istio
    helm:
      valueFiles:
        - values.yaml
        - values-{{ .Values.environment }}.yaml
  syncPolicy:
    automated:
      prune: true
    validate: true
