apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: istio-operator
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/istio/istio.git
    targetRevision: "1.9.5"
    path: manifests/charts/istio-operator
    helm:
      parameters:
        - name: "operatorNamespace"
          value: "istio-operator"
        - name: "istioNamespace"
          value: "istio-system"
  syncPolicy:
    automated:
      prune: true
    validate: true
