apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: linkerd
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/thomasv314/infra-eks.git
    targetRevision: HEAD
    path: applications/linkerd
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: serviceprofiles.linkerd.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - group:  apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: trafficsplits.split.smi-spec.io
      jsonPointers:
        - /spec/preserveUnknownFields
